from enum import Enum

class TopicSourceCode(str, Enum):
    ROLE_REQUIRED = "ROLE_REQUIRED"
    RESUME_SKILL = "RESUME_SKILL"
    PROJECT_EVIDENCE = "PROJECT_EVIDENCE"
    EXPERIENCE_EVIDENCE = "EXPERIENCE_EVIDENCE"
    MODE_REQUIRED = "MODE_REQUIRED"
