import pytest
import uuid
from datetime import datetime, timezone
from unittest.mock import AsyncMock
from app.ai_interview.persistence.repository import InterviewSessionRepository
from app.ai_interview.persistence.exceptions import IdempotencyConflictError
from app.ai_interview.schemas.session import InterviewSessionSchema
from app.ai_interview.question_engine.schemas import QuestionRecord
from app.ai_interview.question_engine.enums import QuestionStatus
from app.ai_interview.answer_engine.schemas import EvaluationRecord
from app.ai_interview.answer_engine.enums import CoverageSignal, FollowUpSignal
from app.ai_interview.core.enums import QuestionType, DifficultyLevel

@pytest.fixture
def mock_collection():
    return AsyncMock()

@pytest.fixture
def repo(mock_collection):
    return InterviewSessionRepository(mock_collection)

@pytest.mark.asyncio
async def test_save_enforces_embedded_idempotency_guard(repo, mock_collection):
    from app.ai_interview.schemas.blueprint import InterviewBlueprint
    blueprint = InterviewBlueprint(
        blueprint_version="1.0",
        total_question_budget=5,
        min_questions=2,
        max_questions=5,
        emergency_max_questions=7,
        topics=[]
    )
    session = InterviewSessionSchema(
        session_id="session-123",
        candidate_id="c-123",
        company_id="comp-123",
        campaign_id="camp-123",
        mode_id="mode-1",
        mode_version=1,
        blueprint=blueprint,
        created_at=datetime.now(timezone.utc)
    )
    
    # Add a question
    q_id = str(uuid.uuid4())
    session.question_history.append(QuestionRecord(
        record_id=q_id,
        session_id=session.session_id,
        turn_number=1,
        topic_id="t1",
        question_text="Q1",
        question_type=QuestionType.INITIAL,
        difficulty=DifficultyLevel.MEDIUM,
        status=QuestionStatus.EVALUATING
    ))
    session.questions_asked_total = 1
    
    # Add an evaluation
    session.evaluation_history.append(EvaluationRecord(
        evaluation_id=str(uuid.uuid4()),
        question_record_id=q_id,
        topic_id="t1",
        overall_score=0.9,
        qualitative_coverage_signal=CoverageSignal.QUALITATIVELY_COVERED,
        follow_up_signal=FollowUpSignal.NONE
    ))
    
    # Setup mock to simulate idempotency guard kicking in
    mock_collection.update_one.return_value.matched_count = 0
    
    async def fake_count_documents(q):
        if "version" in q:
            return 1 # The version matches, so OCC is fine
        return 1 # The document exists
    mock_collection.count_documents.side_effect = fake_count_documents
    
    with pytest.raises(IdempotencyConflictError, match="Database rejected update due to embedded idempotency guard"):
        await repo.save(session, expected_version=1, idempotency_evaluation_question_id=q_id, idempotency_question_id=q_id)
        
    # Verify the query generated by repo includes the $ne guard
    mock_collection.update_one.assert_called_once()
    args, kwargs = mock_collection.update_one.call_args
    query = args[0]
    
    assert query["evaluation_history.question_record_id"] == {"$ne": q_id}
    assert query["question_history.record_id"] == {"$ne": q_id}
