from enum import Enum

class ExtractionQualityStatus(str, Enum):
    USABLE = "USABLE"
    PARTIALLY_USABLE = "PARTIALLY_USABLE"
    UNUSABLE = "UNUSABLE"

class ExtractionWarningCode(str, Enum):
    LOW_TEXT_CONTENT = "LOW_TEXT_CONTENT"
    NO_EDUCATION_DETECTED = "NO_EDUCATION_DETECTED"
    NO_EXPERIENCE_DETECTED = "NO_EXPERIENCE_DETECTED"
    NO_SKILLS_DETECTED = "NO_SKILLS_DETECTED"
    PARTIAL_EXTRACTION = "PARTIAL_EXTRACTION"
